### ISSUE TITLE
OSError: [Errno 20] Not a directory: '/home/adeoluwa/Music/culture.wav/filtered'

### ISSUE THREAD

**Issue by deolu007** [aalireza/SimpleAudioIndexer#5] opened 2017-11-13 16:02 UTC
I entered this command; >>> indexer.index_audio()

and this what I got

OSError: [Errno 20] Not a directory: '/home/adeoluwa/Music/culture.wav/filtered'

**Comment by aalireza** [comment] 2017-11-13 16:50
Please take a look at [here](https://github.com/aalireza/SimpleAudioIndexer/blob/master/CONTRIBUTING.rst#bug-reports) and post here all the information necessary to replicate the problem.

**Comment by aalireza** [comment] 2017-11-16 00:44
I'm closing the request under the assumption that the problem is no longer relevant and wasn't initially a bug, since such error is expected if the `src_dir` of the `indexer` is not a directory which contains `culture.wav`, but `culture.wav` itself. If that's not the case, let me know.

**Closed by aalireza** 2017-11-16 00:44 UTC

**Comment by deolu007** [comment] 2017-11-16 02:47
You're right, it wasn't a directory but the file itself. thanks.

**Comment by aalireza** [comment] 2017-11-16 03:40
@deolu007 

1. I don't know what `after creating a path to the directory itself` means. I assume you meant you changed `src_dir` to be the path to the directory in which `culture.wav` is contained.

2. This is the third time you've raised issues that stem from you not reading the documentation. Read the documentation and raise an issue only if you're confident that the problem is with this software.

3. `ValueError: could not convert string to float: do` is a different issue than this one. Create a new issue if you think it's a problem with `sai`, and for the second time, take a look at (here)[https://github.com/aalireza/SimpleAudioIndexer/blob/master/CONTRIBUTING.rst#bug-reports] and include all the steps required to replicate the issue. You need to include the previous commands, the audio file itself, and practically anything else that's required for me to replicate the error. I neither have access to your computer nor can read your mind to see what you've done and what the cause of the error might be.
